# -*- coding: utf-8 -*-
"""model_build.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_3W4xzXaeGsewW1L1Ypdijue5Hz7qWvY
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier 
from sklearn import metrics
from flask import Flask, request, render_template
import pickle

df=pd.read_csv('employee-churn1.csv')
df.head()

X=df[['satisfaction', 'evaluation', 'number_of_projects',
       'average_montly_hours', 'time_spend_company', 'work_accident', 
       'promotion']]
y=df[['churn','evaluation']]

X.head()

y

y.drop('evaluation',axis=1,inplace=True)

y

df.shape

X.isnull().sum()

X.shape

y.shape

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y)

from sklearn.ensemble import RandomForestRegressor
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train, y_train)

#save the model 
pickle.dump('classifier',open('model.pkl','wb'))

model=pickle.load(open('model.pkl','rb'))

model



t=clf.predict([[0.10,0.8,6,200,4,0,0]])



